project 'JHShow.xcodeproj'

# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'
  inhibit_all_warnings!

target 'JHShow' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for JHShow
  pod 'JHButton'
  pod 'Masonry'
end
